project_id = "ikioetqbrybnofqkdcib"

[functions.receive-from-n8n]
verify_jwt = false

[functions.send-to-n8n]
verify_jwt = false

[functions.log-conversation]
verify_jwt = false

[functions.generate-ai-summary]
verify_jwt = true

[functions.ai-comparison-test]
verify_jwt = true

[functions.claude-ai-agent]
verify_jwt = false

[functions.claude-ai-agent-tools]
verify_jwt = false

[functions.generate-embedding]
verify_jwt = false

[functions.receive-message]
verify_jwt = false

[functions.send-response]
verify_jwt = false

[functions.receive-email]
verify_jwt = false

[functions.send-scheduled-summary]
verify_jwt = false
